spring:
 h2:
  console:
   enabled: true
   path: /h2-console
 datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:testdb
  generate-unique-name: false
    #username: sa
    #password: 1234