spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:testdb
    #generate-unique-name: false
  h2:
    console:
      enabled: true
      #path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop